name: Dev CI Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Commit Message
        id: commit
        run: echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Create PR to main
        if: contains(steps.commit.outputs.msg, 'deploy init')
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: dev
          title: Deploy to Production
          body: Auto deployment triggered by commit message "deploy init"